force-app/main/default/objects/PeriodicidadeVaciacao__mdt/PeriodicidadeVaciacao__mdt.object-meta.xml
<CustomObject>
    <label>Periodicidade de vacinação</label>
    <pluralLabel>Periodicidades de vacinaçôes</pluralLabel>
</CustomObject>

force-app/main/default/objects/PeriodicidadeVaciacao__mdt/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Espécie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cachorro</fullName>
                <default>true</default>
                <label>Cachorro</label>
            </value>
            <value>
                <fullName>Gato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PeriodicidadeVaciacao__mdt/fields/IntervaloDias__c.field-meta.xml
<CustomField>
    <fullName>IntervaloDias__c</fullName>
    <description>Campo numérico que representa o intervalo em
dias que um pet deve ser vacinado</description>
    <inlineHelpText>Campo numérico que representa o intervalo em
dias que um pet deve ser vacinado</inlineHelpText>
    <label>Intervalo em dias</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <displayFormat>PET-{0000}</displayFormat>
        <label>Pet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/DataProximaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataProximaVacinacao__c</fullName>
    <label>Data da próxima vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/DataUltimaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaVacinacao__c</fullName>
    <label>Data da última vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PetBO.cls
public with sharing class PetBO {
    public static void preencheDataVacinacao(List<Pet__c> lstPets){

        set<id> petsId = new set<id>();
        List<Pet__c> petsUpdateVacinacao = new List<Pet__c>();
        
        Map<String,PeriodicidadeVaciacao__mdt> mapPvIntervalo = new Map<String,PeriodicidadeVaciacao__mdt>();
        for(PeriodicidadeVaciacao__mdt pv : [SELECT Id, Label, Especie__c, IntervaloDias__c 
                                            FROM PeriodicidadeVaciacao__mdt ]){
                mapPvIntervalo .put(pv.Especie__c, pv);
        } 

     /*    List<PeriodicidadeVaciacao__mdt> listPeriodoVacina = new List<PeriodicidadeVaciacao__mdt>();
        for(PeriodicidadeVaciacao__mdt pv : [SELECT Id, Label, Especie__c, IntervaloDias__c 
                                            FROM PeriodicidadeVaciacao__mdt ]){
                    listPeriodoVacina.add(pv);
        }  */
        for(Pet__c p : lstPets){
            petsId.add(p.id);
        }

         
        
        for(Pet__c p : PetDAO.getPetIs(petsId)){
            if(p.Especie__c == 'Gato' && p.DataUltimaVacinacao__c != null){
                Integer intervalo = (Integer) mapPvIntervalo.get(p.Especie__c).IntervaloDias__c;
                System.debug('###############Intervalo' + intervalo);
                p.DataProximaVacinacao__c = p.DataUltimaVacinacao__c + intervalo;

            }else{
                Integer intervalo = (Integer) mapPvIntervalo.get(p.Especie__c).IntervaloDias__c;
                p.DataProximaVacinacao__c = p.DataUltimaVacinacao__c + intervalo;
            }
            petsUpdateVacinacao.add(p);
        }

        update petsUpdateVacinacao;


    }
}