force-app/main/default/objects/Adocao__c/Adocao__c.object-meta.xml
<CustomObject>
    <label>Adoção</label>
    <nameField>
        <displayFormat>ADOT-{0000}</displayFormat>
        <label>Adoção Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoçoes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adocao__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adocao__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoções</relationshipLabel>
    <relationshipName>Adocoes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <displayFormat>PET-{0000}</displayFormat>
        <label>Pet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/DataProximaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataProximaVacinacao__c</fullName>
    <label>Data da próxima vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/DataUltimaVacinacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaVacinacao__c</fullName>
    <label>Data da última vacinação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Raca__c.field-meta.xml
<CustomField>
    <fullName>Raca__c</fullName>
    <label>Raça</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Especie__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vira-lata</fullName>
            </value>
            <value>
                <fullName>Poodle</fullName>
            </value>
            <value>
                <fullName>Siamês</fullName>
            </value>
            <value>
                <fullName>Persa</fullName>
            </value>
            <value>
                <fullName>Americam Bully micro</fullName>
            </value>
            <value>
                <fullName>Americam Bully sandard</fullName>
            </value>
            <value>
                <fullName>Americam Bully XL</fullName>
            </value>
            <value>
                <fullName>PitBull</fullName>
            </value>
            <value>
                <fullName>Husk</fullName>
            </value>
            <value>
                <fullName>Buldog Frances</fullName>
            </value>
            <value>
                <fullName>Buldog Americano</fullName>
            </value>
            <value>
                <fullName>America Staforshire</fullName>
            </value>
            <value>
                <fullName>Siberiam</fullName>
            </value>
            <value>
                <fullName>Ragdoll</fullName>
            </value>
            <value>
                <fullName>Siames</fullName>
            </value>
            <value>
                <fullName>Mainecon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PetDAO.cls
public with sharing class PetDAO {
  
    public static Pet__c getPet(String recordId){

        return [SELECT Name, Especie__c, Raca__c, DataUltimaVacinacao__c, DataProximaVacinacao__c,
        (SELECT id, Contact__r.Name, Adocao__c.Name, Pet__r.Name 
        FROM Adocoes__r)
        FROM Pet__c
        WHERE Id =:recordId
        LIMIT 1];

    }

    public static List<Pet__c> getPetIs(Set<id> recordId){

        return [SELECT Name, Especie__c, Raca__c, DataUltimaVacinacao__c, DataProximaVacinacao__c,
        (SELECT id, Contact__r.Name, Adocao__c.Name, Pet__r.Name 
        FROM Adocoes__r)
        FROM Pet__c
        WHERE Id =:recordId
        LIMIT 1];

    }
}